spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: cemaledurak
    password: Mdso&8362$Jds
  jpa:
    show-sql: true